### ISSUE TITLE
Bug: request parsing only checks first commit in array

### ISSUE THREAD

**Issue by Atema** [Atema/DD2480-CI#30]
In the function `BuildRequestServlet#JsonParsing`, the commit sha is taken from the first item in the commits list. However, this list may maybe be empty, and that would result in an error (although that's not much of a problem, since it would fail softly.
More important: I'm not sure whether the first item in the commits list is the latest or the oldest commit that is part of the push. If it 's the latest, everything is fine. Otherwise, we build the wrong thing. It may be easier to use the SHA stored in `after` (in the main object) instead.

**Comment by linnea-bonnevier** [comment]
That's a good question that I did not think about, I assume that the latest commit is first but however that would not be reasonable since it is an array... I'll look into it

**Comment by Atema** [comment]
Thanks. If you change it, I think it would be good to also change the `nameAuthor` and `emailAuthor` to the values from the `pusher` object in the JSON
